package:
  name: pptcom
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - python
    - comtypes

test:
  imports:
    - pptcom
  requires:
    - pytest
    - python-pptx
  commands:
    - py.test --pyargs pptcom

about:
  home: https://github.com/m-rossi/pptcom
  license: MIT
  summary: Use Microsoft PowerPoint within Python with the help of COM
